### PR TITLE
Translated the "introduction" chapter to Ukrainian

### PR DESCRIPTION
**Pull request by gatamar**
Hello, @Pomax! 
I'm happy to contribute to your repo. 

I've added a translation of one chapter to Ukrainian language.
While I'm a little bit confused: it seems, a current project structure is different from described here: https://github.com/Pomax/BezierInfo-2/wiki/localize#localization
So I wasn't able to find a file "locale-strings.js".  

Please notify me if there's something I should improve in order to this PR to be merged.

### CODE REVIEW

**Comment by Pomax** [comment]
Thank you very much for starting that work! Note that the locaIt's a direct link to the correct file, though: it's in the `src` folder:

image

**Review by Pomax — CHANGES_REQUESTED** [review]
If you can add in the locale-string.js changes, too, I can generate a new copy of the primer with Ukranian started =)

**Comment by gatamar** [comment]
I'm trying to close this, please look at https://github.com/Pomax/BezierInfo-2/pull/275

**Comment by Pomax** [comment]
You... didn't have to close this? Just update your branch, and the PR automatically picks up the new commits. That's how PR review works: fixes are just more commits on the same branch.

**Comment by gatamar** [comment]
@Pomax Sorry again :)
My "old" forked repo couldn't be updated with `git pull`\`git merge`. 
It seems, I should had use smth like `git upstream`, but I thought it would be faster to re-fork :)

**Comment by Pomax** [comment]
yeah, definitely.

**Pull request closed without merging**
