### PR TITLE
[ko-KR] Chapter 3 translation

### PR DESCRIPTION
**Pull request by EatChangmyeong**
I've translated chapter 3 ("The mathematics of Bézier curves") into ko-KR.

Meanwhile I learnt to run `git pull https://github.com/Pomax/BezierInfo-2` directly on my `master` branch (without opening a pull request) and `cherry-pick` on the new branch, so hopefully "Merge branch 'blah' into 'blah'" and previous commits will show up less frequently next time. I'm sorry if this bothered you.

### CODE REVIEW

**Comment by Pomax** [comment]
The by far easier way to do this is to make sure you have this repo as a "remote". To check if you do, run:

```
$ git remote -v
```

If you don't have this repo, you can easily add it using:

```
$ git remote add pomax git@github.com:Pomax/Bezierinfo-2
```

Once you have that set up, you can always get your `master` branch synced to "whatever the official master branch is" by using:

```
$ git fetch pomax
$ git checkout -B master pomax/master
```

The first command checks this repo for its current commit tree, and the second command  deleted your current master branch and then immediately makes a new master branch based on `pomax/master`.

**Comment by EatChangmyeong** [comment]
Thank you for the detailed explanation -- actually this is the first time I used the `remote` command and realized how useful it is.

**Comment by EatChangmyeong** [comment]
So anyway -- I'd like to know if the pull request is good, or have some other problems I have to fix.

**Comment by Pomax** [comment]
Hiya - I haven't forgotten about this, but I suffered an arm injury a while back and I'm still recovering from that.

**Comment by EatChangmyeong** [comment]
I'm sorry to hear that -- I hope that you'll get well soon.

**Comment by Pomax** [comment]
I can finally actually use my arm and hand again, so I will try to get this reviewed today =)

**Comment by Pomax** [comment]
sorry that this took so long!

**Review by Pomax — APPROVED** [review]
thank you so much for your patience

**Pull request merged**
