### PR TITLE
add extended

### PR DESCRIPTION
**Pull request by thrillerist**

### CODE REVIEW

**Comment by Pomax** [comment]
thanks for your continued help!

**Comment by thrillerist** [comment]
you can buy me a coffee, haha

**Comment by Pomax** [comment]
sounds perfectly fair to me. how much is a coffee and where do I paypal it to =)

**Comment by thrillerist** [comment]
whatever you like XD
https://www.paypal.me/thrillerist

**Comment by Pomax** [comment]
quite.

**Comment by thrillerist** [comment]
thanks =)

**Pull request merged**
