### PR TITLE
[ko-KR] Chapter 2 translation

### PR DESCRIPTION
**Pull request by EatChangmyeong**
I've translated chapter 2 ("So what makes a Bézier Curve?") into ko-KR, but unfortunately this one can't be merged right away.

I also tried translating the math text into Korean (because the Japanese and Russian version also did this), but the LaTeX engine seemingly could't handle Hangul:

image

Once this issue is solved or we decide to revert it back to English, I'll undraft this pull request and fetch upstream commits.

### CODE REVIEW

**Comment by Pomax** [comment]
Yep, I was waiting for that one to pop up: for CJK languages there's a section in the latex converter here: https://github.com/Pomax/BezierInfo-2/blob/master/src/build/markdown/processors/latex/latex-to-svg.js#L52-L84

So let's see if there's a suitable font in the standard TeX distributions that we can use to typeset maths with Korean text in it.

**Comment by Pomax** [comment]
Do any of the fonts in https://ctan.org/pkg/unfonts-core look decent enough? If so, it'll be pretty easy to add whichever looks best, in (note that the font for maths latex is meant to look more "textbookish" than the page's own font, so we're not looking for the same kind of Noto styling here).

**Comment by Pomax** [comment]
Alternatively, there's also the https://ctan.org/pkg/baekmuk collection

**Comment by EatChangmyeong** [comment]
I've read your code and some fonts you recommended, and I have some question:

* Does XeLaTeX support arbitrary font files? If so, where should I place the font files? It seems like the repository lacks fonts (`gbsn00lp.ttf` and `ipaexm.ttf`) specified in latex-to-svg.js.
* UnBatang looks good, but unfortunately it seems to be licensed under GNU GPL v2 **without font embedding exception**.
* Baekmuk Batang also looks good, and we only have to add the following copyright notice:
```
Copyright (c) 1986-2002 Kim Jeong-Hwan
All rights reserved.

Permission to use, copy, modify and distribute this font is
hereby granted, provided that both the copyright notice and
this permission notice appear in all copies of the font,
derivative works or modified versions, and that the following
acknowledgement appear in supporting documentation:
    Baekmuk Batang, Baekmuk Dotum, Baekmuk Gulim, and
    Baekmuk Headline are registered trademarks owned by
    Kim Jeong-Hwan.
```
* If other fonts are also supported, [Noto Serif Korean](https://fonts.google.com/noto/specimen/Noto+Serif+KR), [나눔명조(Nanum Myeongjo)](https://hangeul.naver.com/2021/fonts/nanum), [마루 부리(Maru Buri)](https://hangeul.naver.com/2021/fonts/maru) are also good choices, and they're all licensed under OFL 1.1.

For now, I'd like to get it working on my local machine first, and then I can compare how these fonts look on the actual document.

**Comment by Pomax** [comment]
> Does XeLaTeX support arbitrary font files? If so, where should I place the font files? It seems like the repository lacks fonts (gbsn00lp.ttf and ipaexm.ttf) specified in latex-to-svg.js.

It does, but anything that gets installed as package doesn't need you to put fonts anywhere, they're going to be installed in a TeX-managed location and simply loading the font by its known filename will work (Which is how the Chinese and Japanese fonts get loaded).

> UnBatang looks good, but unfortunately it seems to be licensed under GNU GPL v2 without font embedding exception.

That's fine: we're not embedding them. XeLaTeX creates a PDF file only as intermediary to get us to an image.

> Baekmuk Batang also looks good, and we only have to add the following copyright notice:

Same here: we're only using these fonts to generate images, not redistributing (even part of) them.

**Comment by Pomax** [comment]
In order to make them work we need a new section in the LaTeX converter that is the same as for Chinese and Japanese, just with the font changed to the correct name (and the locale conditional checking for Korean of course). The README will then also need to be updated to mention which TeX package needs to be installed to make sure that font's available, which is mentioned [here](https://github.com/Pomax/BezierInfo-2/blob/master/README.md?plain=1#L9-L28)

**Comment by EatChangmyeong** [comment]
Thank you, now I roughly understand how it works. I'll try UnBatang and Baekmuk Batang later today.

**Comment by EatChangmyeong** [comment]
I've installed the `texlive-lang-korean` package as an additional dependency and got it almost working in the meantime. XeLaTeX somehow ignores whitespace so I had to prepend backslashes to all whitespace characters.
Following images are the rendered SVGs (uploaded here as PNGs) with `batang.ttf` and `UnBatang.ttf` respectively:

batang.ttf
UnBatang.ttf

`UnBatang.ttf` looks clearer to me, so I guess I'll stick to it. I also want to try out `nanumtype1` but I don't know which filename should be used for `\setCJKmainfont`.

**Comment by Pomax** [comment]
That doesn't sound right. Spaces should not need escaping inside `textit` as the whole point of that command is to use normal typesetting rules instead of maths rules... let's find out what's going wrong there.

**Comment by Pomax** [comment]
Looks like we just need to add the `\CJKspace`  command:

image

So in the latex-to-svg file:

```javascript
    // For Korean we need xeCJK but we need to make sure to enable spaces
    // so that text doesn't get collapsed during typesetting.
    if (locale === "ko-KR") {
      fonts = `
        \\usepackage{xeCJK}
        \\xeCJKsetup{CJKmath=true}
        \\setCJKmainfont{UnBatang.ttf}
        \\CJKspace
      `;
    }
```

**Comment by Pomax** [comment]
Also, as this introduces new installation requirements, let's update the README.md so that "building everything" reads:
```
## Building everything

Use the active Node LTS (currently v14) or higher, with all the project dependencies installed via `npm install`. Note that [node-canvas](https://github.com/Automattic/node-canva) will need you to [install some Cairo libs/headers](https://github.com/Automattic/node-canvas#compiling) using your OS's package manager, with [special instructions for Windows users](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows) because Windows doesn't come with the same kind of package management that Unixy systems do. To successfully compile, GTK is _required_, but JPEG support is not (this repo's code only generates PNG images).

Also note that you will need a TeX installation with several dependencies: on Windows, install [MiKTeX](https://miktex.org/download) and set it up so that it automatically installs things as needed. On Linux/Unix/etc, you'll need to install the following packages :

- xzdec
- libpoppler-glib-dev

And for the LaTeX work you will need:

- texlive
- texlive-xetex
- texlive-extra-utils
- fonts-unfonts-core
- pdf2svg

To make life easier, if your distro uses apt-get, just run this:

```
> sudo apt-get update && sudo apt-get install xzdec libpoppler-glib-dev texlive texlive-xetex texlive-extra-utils pdf2svg
```

If you're using a different package installation method, note that for LaTeX you will need `xetex`, `pdfcrop`, and the following fonts (installed using a TeX distribution manager):

- Linux Libertine
- XITS Math
- TeX Gyre
- TeX Gyre Math
- Arphic-ttf
- IPAex (_not_ type1)
- UnBatang

Note: [pdf2svg](https://github.com/dawbarton/pdf2svg/), can be installed just like everything else on Linux, but on Windows requires you to build the tool yourself, after which you will have to put the pdf2svg.exe file somewhere sensible (like `C:\Program Files (x86)\pdf2svg`) add then manually add its directory to your PATH environment variable, so that windows knows where to look when the `pdf2svg` command gets issued.

With all the dependencies in place, you can now continuous-test everything using:

```
> npm test
```

Which will start the build run in "watch" mode, opening a browser with the compiled project, and recompiling as you update and save files.

To run a single, full build, rather than continuous building, use:

```
> npm start
```

Note that for dev work, you typically want to run `npm test` for as long as you're working on that code. Once you're ready to form a commit for PR purposes, run `npm start` to do a "real" build rather than a dev build, and then form your commit, so that you're pushing "final" code rather than intermediate dev code.
```

**Comment by EatChangmyeong** [comment]
Thank you, now the spacing works fine; I also updated README.md so please check if I edited it correctly.

With all the changes, this pull request is **finally** ready for review! 🎉

**Comment by EatChangmyeong** [comment]
Just a quick question out of curiosity -- is there a command that force regenerates all/some of the math images? Or do I have to manually delete corresponding files in `/docs/images/chapters`?

**Comment by Pomax** [comment]
You'll have to delete the images and then rerun. I use a file manager that shows dates right next to the filenames, so I usually  just set it to sort by date, delete all from "the last X hours" and then set it back to sorting by extension/name. That way you don't have to delete every single image.

**Review by Pomax — APPROVED** [review]

**Comment by Pomax** [comment]
In it goes - for any next work, remember to first delete your translation branch, then sync your master branch to this repo's, and then branch off of your updated master again before starting a new translation.

**Pull request merged**
