### PR TITLE
Fix bug in pseudocode. The same variable was referred to using different identifiers

### PR DESCRIPTION
**Pull request by krofna**

### CODE REVIEW

**Comment by Pomax** [comment]
Please give PRs a good title and PR comment, not just "this makes more sense" without an actual comment to explain the fix.

**Comment by krofna** [comment]
Sorry. In the loop there are lines line(coords, _coords) and coords = _coords which imply that this variable was supposed to be named coords, not coord.

**Comment by Pomax** [comment]
Good point. Reading the code, it's probably to keep it `coord` and instead instead remove the `s` from `coords` and `_coords`, since both aliasses are used to refer to individual coordinates rather than (small) sets.

**Comment by Pomax** [comment]
nice, thanks!

**Pull request merged**
