### PR TITLE
typo

### PR DESCRIPTION
**Pull request by gabyx**

### CODE REVIEW

**Comment by Pomax** [comment]
oh good catch, thanks!

**Comment by winduptoy** [comment]
@Pomax This typo is indeed fixed, but the SVG rendered version of the formula at https://pomax.github.io/bezierinfo/#matrixsplit hasn't been updated! Caused me lots of head scratching...

**Comment by Pomax** [comment]
I merged this in while on vacation, forgot to generate a new copy (it's not tied into CI atm) when I got back home. Let me do that right now.

**Comment by Pomax** [comment]
rebuilt - might take a few minutes for github.io to catch up on the changes

**Pull request merged**
