### PR TITLE
[ja-JP] Translate extended

### PR DESCRIPTION
**Pull request by mashabow**

### CODE REVIEW

**Comment by Pomax** [comment]
awesome work, thanks for the continued help!

**Comment by Pomax** [comment]
Do you have a paypal account that I can send some coffee money to, too? =)

**Comment by mashabow** [comment]
Unfortunately I have no such account, but no problem: I've just bought you an imaginary coffee, so you can send me an imaginary coffee, too =)

**Comment by Pomax** [comment]
can do, and thank you again =)

**Pull request merged**
